#
# MAKEFILE
# Autors: Petr Buno
#

all: help
	
	
help:
	echo -e "Dokumentaci pomoci doxygenu vytvorite prikazem:\n make docs"
	
docs:
	doxygen IntelligentHomeAnywhere.doxyfile
	
clean:
	rm -rf html
	rm -rf latex